### ISSUE TITLE
CHALLENGE: Reduce the build size of these demos

### ISSUE THREAD

**Issue by pranaygp** [zeit/now-examples#11]
There are a lot of benefits in having really small Docker images. One benefit is that it's much faster to ship, start and scale a docker deployment on [Now](https://now.sh) if it has a smaller image size.

You can find a list of all the current docker image sizes in this repo from the [README](https://github.com/zeit/now-examples#overview-1). Some of these images are as small as `12KB` 🤯 

We've tried to keep these images pretty small, but there's always more room for improvement, and this makes for a great challenge. Take a swing at making these images even smaller (without losing functionality). 

Some places to start:

1. Look for a smaller base image that provides the same functionality. For example, `mhart/alpine-node` comes with `npm` and `yarn` which aren't necessary to run a Node app. once the dependencies are installed, you can use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to switch to a `base` tag like [here](https://github.com/zeit/now-examples/blob/e6dd79b4c3da6d66223fc228aa74c4d877981b52/node-micro/Dockerfile#L9)
2. Compile (and strip?) a binary, before using a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to create a container from `scratch` and simply copy over the binary like [here](https://github.com/zeit/now-examples/blob/master/crystal-hello/Dockerfile)
3. Write a `.dockerignore` file that uses a whitelist to remove unnecessary files in the image like [here](https://github.com/zeit/now-examples/blob/master/misc-chat-roulette/.dockerignore). Fun fact, by not doing this, you might be copying over folders like `.git` into your image that you don't need at runtime

Godspeed

**Comment by joecohens** [comment]
Thank you so much for the effort you have put into this issue! 😊

We are closing it for now since it is not applicable to our newest release Now 2.0.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
