### ISSUE TITLE
[question] Support, or lack thereof, for non-http transport?

### ISSUE THREAD

**Issue by avishayp** [zeit/now-examples#110]
I'd "convert" to a paid customer immediately if `now` supported non-HTTP transport. I don't see any indication of that in examples/docs, and my test deployment indeed failed. Could someone clarify if this is/will be supported?

**Comment by jamo** [comment]
Only HTTPS and WSS traffic over port 443 are currently supported.

What's the specific protocol and usecase you are looking for?

**Comment by avishayp** [comment]
@jamo it is pretty common for IoT devices to use mqtt or raw tcp or udp. There is currently no straightforward way to quickly deploy a public non http server, and I think ‘now’ is well positioned to provide that.

**Comment by avishayp** [comment]
Closing as the question was answered.
