### ISSUE TITLE
Go example lacking

### ISSUE THREAD

**Issue by Hades32** [zeit/now-examples#117]
It's unclear if "go.mod" is supported or dependencies at all.

As with most frameworks (like Martini or GinGonic) you typically start a complete HTTP server it would be great to see an integration example

**Comment by bluebeel** [comment]
For the moment I do not see the interest of the functions for go..
How do we integrate our middlewares? Should we move this in the Handler function?

**Comment by bluebeel** [comment]
After reading the source code, I think it's easy to improve the now / go.
For example for middlewares, we can give them a name also in particular eg: **Middleware1**, **Middleware2**,... 
In this way with the AST parser defined [here](https://github.com/zeit/now-builders/blob/master/now-go/util/get-exported-function-name.go) we can recover their names and thus only have to modify the main.go file of the builder to wrap our handler with these middlewares.

In order for this to work, we need to define a middleware type. It can be defined as:
```go
// middleware provides a convenient mechanism for filtering HTTP requests
// entering the application. It returns a new handler which may perform various
// operations and should finish by calling the next HTTP handler.
type middleware func(next http.HandlerFunc) http.HandlerFunc
```
Using this pattern we define the middlewares as such:
```go
func Middleware1(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		log.Printf("Logged connection from %s", r.RemoteAddr)
		next.ServeHTTP(w, r)
	}
}

func Middleware2(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		log.Printf("Tracing request for %s", r.RequestURI)
		next.ServeHTTP(w, r)
	}
}
```
We provide a chain function for chaining multiple middleware into one.

```go
// chainMiddleware provides syntactic sugar to create a new middleware
// which will be the result of chaining the ones received as parameters.
func chainMiddleware(mw ...middleware) middleware {
	return func(final http.HandlerFunc) http.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) {
			last := final
			for i := len(mw) - 1; i >= 0; i-- {
				last = mw[i](last)
			}
			last(w, r)
		}
	}
}
```

**Comment by bluebeel** [comment]
I made 2 PR for this implementation [**PR#3**](https://github.com/zeit/now-builders/pull/3) and **#118**

**Comment by timothyis** [comment]
Apologies for the silence here. I agree that the Go example is indeed lacking. We will work on making it better. We'll start off by reviewing your PRs @bluebeel! Thank you so much for those.

Any other feedback of what you'd like to see in a basic or advanced example would be very helpful for us 🙏
