### ISSUE TITLE
Use WordPress as a Backend to Next.js App (Headless WordPress)

### ISSUE THREAD

**Issue by cr101** [zeit/now-examples#123]
I'm building a Next.js web app that uses WordPress as a backend.

Is it possible to host both the Next.js frontend and the WP backend on Now 2.0? The URL for the frontend would be https://mywebapp.com and the URL for the WP backend would be https://wp.mywebapp.com

**Comment by rauchg** [comment]
We anticipate running WordPress _might_ be possible with `@now/php`, but we haven't investigated deeply enough to guarantee that it will and that it would be recommended for production yet.

That said, highly scalable Next.js and React SSR is definitely a huge priority.

**Comment by rauchg** [comment]
If you (or any one reading) want to look into this, I recommend investigating:
- Bundling `.php` sources together based on entrypoint and the analysis of its dependency tree (e.g.: stitching together all the `include` and `require` calls)
- What extensions are necessary for the `php` runtime that are currently missing. Here's a `phpinfo` I just deployed for reference: https://phpinfo-5zl67pq66.now.sh

**Comment by timothyis** [comment]
The good news is that @now/wp is available! I'll be working on documenting this very shortly and then we can work on an example and [guide](https://zeit.co/guide) for this! Thank you very much for the suggestion.

**Comment by fredski02** [comment]
@timothyis How is @now/wp coming along?

**Comment by timothyis** [comment]
Hi @fredski02. Sorry for the delay, but the good news is that we're very close to merging the documentation for the WordPress builder: https://github.com/zeit/docs/pull/549

I'll be reviewing this today and making any necessary changes so we can merge it in 🙏

**Comment by homerjam** [comment]
Please can you add an example of how to enable uploads (even if only to `/tmp`)?

**Comment by Emiliano-Bucci** [comment]
Is there an update on this? :)

**Comment by timothyis** [comment]
Hi @Emiliano-Bucci! We're working on creating documentation and guides for WordPress as we speak. This will be part of it. I'll ping here when there's an update! 🙏

**Comment by Emiliano-Bucci** [comment]
@timothyis Thanks for the quick answer! I'm very exciting with this new possibility, it seems amazing :)

**Comment by Emiliano-Bucci** [comment]
@timothyis Just a question: With @now/wordpress we are going to be able to mix, for example, next js and wordpress to be able to use all kind of beauty stuff like Graphql, apollo, etc? Or is just Wordpress side? Thanks! :)

**Comment by revskill10** [comment]
One plus for this example. It would be a dream to have a serverless, headless CMS backed by now ;)

**Comment by homerjam** [comment]
I have headless WordPress backed by AWS S3 and RDS working. [This PR](https://github.com/zeit/now-builders/pull/322) is required to make it possible.
