### ISSUE TITLE
Failing to get a static build to work correctly

### ISSUE THREAD

**Issue by mfklauberg** [zeit/now-examples#124]
Hello!

First of all, thank you for an amazing product!

I've been trying to make the static website example to work, as demonstrated by this example:
https://github.com/zeit/now-examples/tree/master/static, but every time that I run `now`, the main deployed URL just show me the css source code, as can be seem here: https://static-nlbvleby1.now.sh.

If I append a `/index.html` to the URL like so: https://static-nlbvleby1.now.sh/index.html, the page renders as expected.

I'm missing something in the source code, or this is the indented behaviour?

thanks!

**Comment by OlliV** [comment]
It's currently expected behavior because currently we filter by `/(.*\/|^)index((\.[^.]+)+$|$)/` and select the first matching file in alphabetical order. It seems we need to rethink that matching logic.

**Comment by mfklauberg** [comment]
So if I change my `index.css` file to something like `styles.css` it should work properly?

**Comment by rauchg** [comment]
Good find @OlliV – I thought the file was `index.css`. Maybe we should have the algorithm be:
- `index.html` first
- `index.*` sorted alphabetically

**Comment by mfklauberg** [comment]
I will close the issue since the problem was a interpretation mistake on my part. Thanks for all the help!
