### ISSUE TITLE
Next.js `export` example is missing `react` and `react-dom` dependencies

### ISSUE THREAD

**Issue by NathanielHill** [zeit/now-examples#131]
Maybe there was supposed to be some magic that I'm unaware of, but this was failing for me and it sure seems like these are peer dependencies of `next` and should be necessary. I've submitted a pull request #130

**Comment by NathanielHill** [comment]
@timneutkens

**Comment by timneutkens** [comment]
Both would work equally, just not when react/react-dom are missing.

**Comment by NathanielHill** [comment]
Cool, I was wondering if you had to specify `package.json` so that it would use the `now-build` script to run `next export`

**Comment by NathanielHill** [comment]
:thinking: Hmmm, I tried it with `next.config.js` instead, and I get no output (just a directory listing).

**Comment by timneutkens** [comment]
@NathanielHill sorry I got confused with `@now/next`, you have to provide package.json when using the static builder.

**Comment by NathanielHill** [comment]
Cool. So `@now/static-build` should be able to do any arbitrary build process then? It just invokes `yarn now-build` correct? When I look up the package on npm, it has no README or repository shown.

**Comment by timneutkens** [comment]
Correct, here's the source: https://github.com/zeit/now-builders/blob/master/packages/now-static-build/index.js
