### ISSUE TITLE
Add Hapijs Example

### ISSUE THREAD

**Issue by mscoutermarsh** [zeit/now-examples#143]
Would be great to have an example with https://hapijs.com/ using the `node-server` build.

If I get something working, I'll open a PR. If someone else does first, that'd be great too!

**Comment by paulogdm** [comment]
Nice suggestion! 
Working on it!

**Comment by mscoutermarsh** [comment]
@paulogdm awesome! 😍

**Comment by paulogdm** [comment]
This is now working! I will open a PR.

**Comment by mscoutermarsh** [comment]
@paulogdm nice!!!!!!!

**Comment by joecohens** [comment]
Closing this one since it was added in https://github.com/zeit/now-examples/pull/156

**Comment by barbalex** [comment]
Why can't I find the example on https://github.com/zeit/now-examples?
