### ISSUE TITLE
Create-React-App ServiceWorker registration failed

### ISSUE THREAD

**Issue by human909** [zeit/now-examples#147]
Hi all,
when changing `unregister()` to `register()` in `./src/index.js` to activate service workers, then deploy the example, serviceWorker.js break about a wrong Mime Type.

(Chrome 70 Mac)
`Error during service worker registration: DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').`

**Comment by human909** [comment]
Hi, thank you.
I think it is about serving correctly files and folders from “public”
folder.
I added routes in now.json for services-worker.js, with max-age, also for
remaining files like robots.txt, favicons etc...
Magic regex and docs could be helpful.
Thank you.

**Comment by human909** [comment]
fixes all errors in prod mode
````
    {"src": "^/asset-manifest.json", "dest": "/asset-manifest.json"},
    {"src": "^/manifest.json", "dest": "/manifest.json"},
    {"src": "^/service-worker.js", "headers": {"cache-control": "s-maxage=0"}, "dest": "/service-worker.js"},
    {"src": "^/precache-manifest.(.*)", "dest": "/precache-manifest.$1"},
````

**Comment by joecohens** [comment]
Hey @human909, this is also a great solution too, thanks for sharing it! We removed the catch all route so that even the favicon.ico can be loaded you can see it here https://github.com/zeit/now-examples/pull/149
