### ISSUE TITLE
Add NextJS with custom-server example

### ISSUE THREAD

**Issue by revskill10** [zeit/now-examples#150]
Is there any way to provide custom server for an existing NextJS project ?
In my case, i have to use custom express server with i18next middleware.

**Comment by TLevesque** [comment]
+1 I'm trying to get deploy the simple next-koa example (https://github.com/zeit/next.js/tree/master/examples/custom-server-koa) and I don't find any now.json config which works for it, like bellow ```{
  "version": 2,
  "name": "now-koa",
  "builds": [
    {
      "src": "*.js",
      "use": "@now/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "/index.js"
    }
  ]
}```

**Comment by TLevesque** [comment]
Got next+koa example working (https://github.com/zeit/next.js/tree/master/examples/custom-server-koa) working, by adding **now.json** file with ```{
  "version": 2,
  "name": "now-koa",
  "builds": [
    {
      "src": "server.js",
      "use": "@now/node"
    },
    {
      "src": "next.config.js",
      "use": "@now/next"
    }
  ]
}``` and **next.config.js** file with ```module.exports = {};``` Would be nice if someone from zeit confirm that it's the right setup.

**Comment by martonlanga** [comment]
They recommended me the monorepo example
https://spectrum.chat/zeit/now/how-to-deploy-next-js-app-with-custom-express-server-to-now-v2~ab4b1807-b516-41f5-a4ec-986036212c14

**Comment by littletower** [comment]
I'm trying to make the i18n example work https://github.com/zeit/next.js/tree/canary/examples/with-next-i18next
so far without success... some additional docs on how to deploy NextJS with a custom server would be greatly appreciated.

**Comment by specialdin** [comment]
Heres an example of next.js using Now 2.0 serverless functions if anyone needs it.
https://github.com/specialdin/nextjs-serverless-now

**Comment by revskill10** [comment]
Since `now` already supports express, i'll close this issue.

**Comment by Semigradsky** [comment]
@revskill10 could you reopen issue? We need example when express server generating internationalized html files like here: https://github.com/isaachinman/next-i18next/blob/master/examples/simple/server.js

**Comment by revskill10** [comment]
@Semigradsky `next-i18next` doesn't support Now serverless deployment [link](https://github.com/isaachinman/next-i18next/issues/25) . So i think this is not Now issue.
Also, the example you provided should work with `@now/node-server` .
