### ISSUE TITLE
Would love to see an example with Angular 6+

### ISSUE THREAD

**Issue by mtin79** [zeit/now-examples#152]

**Comment by mtin79** [comment]
Angular 6 and 7 would be great as an example.

**Comment by timothyis** [comment]
I agree, @mtin79! It's on my list personally!

**Comment by ganny26** [comment]
I have created a simple angular 7 app with routing logic implemented --> PR #288 

https://zeit-angular-app-gksnyrvbi.now.sh

**Comment by msweeneydev** [comment]
Hey @mtin79, this has been added with #423 🎉
