### ISSUE TITLE
How to run examples locally?

### ISSUE THREAD

**Issue by qgustavor** [zeit/now-examples#161]
I used to test locally before deploying on now.sh for testing, often using [micro](https://github.com/zeit/micro). Some examples can be run locally without issues: the index.php from [the PHP 7 example](https://github.com/zeit/now-examples/tree/master/php-7) can be tested in a Apache server without issues.

But the issue raises when Now expects a handler, like on [the Python](https://github.com/zeit/now-examples/tree/master/python) or [the Node.js](https://github.com/zeit/now-examples/tree/master/nodejs) examples. Trying to run `python3 index.py` or `node index.js` does nothing.

How can those functions be tested quickly without having to deploy those (which takes almost a minute)?

I did some tests based on the Node.js example: the `index.js` file is quite similar to [the first example from micro](https://github.com/zeit/micro#usage) so I thought it could work like micro, but it don't works with promises like micro so seems it just runs something equivalent to `http.createServer(require('path to index.js')).listen(port)` internally. Deploying `const { run } = require('micro'); module.exports = (req, res) => run(req, res, () => 'Welcome to Micro')` worked as expected. This behavior could be documented or better explained.

**Comment by visini** [comment]
Hey @qgustavor I have created a tutorial for python, see here: 

Barebone Serverless Python JSON API on Zeit Now
https://medium.com/@camillovisini/barebone-serverless-python-json-api-on-zeit-now-b90187021fb7

Or check out the repo directly: https://github.com/visini/barebone-serverless-api-zeit-now

In the tutorial you can see how you can test the individual routes locally before deploying them to Zeit Now. Let me know if you have any questions!

**Comment by LightningK0ala** [comment]
Really want to get into serverless with now but not knowing how to run things locally is blocking me.
Does it need something [serverless-offline](https://github.com/dherault/serverless-offline)?
Looking forward for updates @rauchg!

**Comment by toddheslin** [comment]
Nice solution @JesusCrow 

If anyone has a relatively simple setup, you can take the easy bits from this:

1) Install `npm i -D micro-dev`
2) Setup a script: `dev:[function name]` with the value `micro-dev <path-to-function>` so you can easily run `npm run dev:somefunction`

If you need access to the env vars, I recommend just setting up the `.env` file and using `dotenv` or `dotenv-safe`, throwing this line at the top of the function code:
`if (process.env.NODE_ENV === 'development') require('dotenv').config`

@JesusCrow's solution works better when you have a lot of functions but this seems to work fine when you just have a few

**Comment by pie6k** [comment]
It gets tricky when you manage credentials with `now secrets`. Technically you can copy them over to `.env` but it's ideally reverse to what `now secrets` is supposed to help with.

**Comment by timothyis** [comment]
Hi all! Apologies for the silence. We have been hard at work making `now dev` for you all. Since there is an open PR for `now dev` in the Now CLI repository, I'll close this issue so there is a single source of information.

Please follow the PR for updates! https://github.com/zeit/now-cli/pull/1883
