### ISSUE TITLE
zeit.co/examples doesn't work

### ISSUE THREAD

**Issue by panr** [zeit/now-examples#171]
https://zeit.co/examples/ doesn't work since yesterday 😓

**Comment by paulogdm** [comment]
Thank you for reporting! We are taking a look!

**Comment by timothyis** [comment]
Thanks, @panr. Sorry about that!
I've just pushed a fix and it'll be live shortly.

**Comment by timothyis** [comment]
Fixed! https://zeit.co/examples

**Comment by panr** [comment]
Thanks guys 👌🏻
