### ISSUE TITLE
Cannot deploy to Now.sh

### ISSUE THREAD

**Issue by marine1079** [zeit/now-examples#174]
I'm trying to clone and deploy the project : [next-pwa](https://github.com/drenther/next-pwa)

And I added just 1 file. (now.json)
![image](https://user-images.githubusercontent.com/14011993/49190209-b9b35280-f3b4-11e8-8801-5496d43b4bbe.png)

But deploy didn't lead to page/index.js so that I couldn't access the index file.
What was wrong with now.json ?
(Please check the github link above. It's hard for me to make right now.json file.)

**Comment by paulogdm** [comment]
Can you try:
```
{
  "version": 2,
...
}
```

**Comment by marine1079** [comment]
It’s just mistake(not version but name). I’ve tried “version”:2.
Please help me.

**Comment by paulogdm** [comment]
Let me take a look at the repo.

**Comment by paulogdm** [comment]
Running `next build --lambdas` I can repro the issue. It seems it is a problem with next.
Check this thread: https://spectrum.chat/?t=032874b9-4d32-4180-bc2e-64478016b736
We are investigating and a solution will be out soon.

**Comment by marine1079** [comment]
Thanks a lot.
I’ll wait for good news.

**Comment by paulogdm** [comment]
We have identified the issue. AVJ was indeed the culprit and a solution is on the Spectrum thread.

**Comment by marine1079** [comment]
Sounds great. Thank you.
