### ISSUE TITLE
Sapper example

### ISSUE THREAD

**Issue by antony** [zeit/now-examples#193]
Would be great to have an example of running Sapper on now v2. I have some fairly extensive apps I would like to migrate to v2.

**Comment by rauchg** [comment]
Indeed! Sapper is a great fit for serverless 😌

**Comment by NathanielHill** [comment]
I believe this is a priority after Svelte 3 lands.

@Rich-Harris ?

**Comment by matt3224** [comment]
Any update on this?

**Comment by timothyis** [comment]
@matt3224 Please feel free to submit a PR with an example. We'd love to have it. Otherwise, we'll be working on this as soon as possible.

**Comment by konsumer** [comment]
I added a PR for the basic sapper demo as a now 2 static-build app.

**Comment by rof20004** [comment]
About sapper-ssr? Like vue-ssr will be good too :)

**Comment by antony** [comment]
@rof20004 Sapper is Svelte + SSR. There is no need for sapper-ssr, it is SSR anyway.

**Comment by rof20004** [comment]
@antony Sorry, I will explain better:

This template(zeit-now) is about hosting a sapper static(exported) website on now, I am asking about hosting sapper project with SSR support on now.

**Comment by antony** [comment]
@rof20004 Ah yes - a fair point.

I would suggest

`sapper-export`
and
`sapper`

in that case.

**Comment by controversial** [comment]
@antony A solution relying on `sapper export` isn’t sufficient in all cases. Using the `static-build` builder works for relatively static apps, but some apps require `sapper build` instead, which generates a node app.

**Comment by rauchg** [comment]
@controversial it'd be great for sapper to be able to generate serverless functions as well in that case. I think for the moment we need to recommend `sapper export` instead?

**Comment by NathanielHill** [comment]
@rauchg @Rich-Harris

I think part of the problem with going serverless is that there is no default `server.js` in Sapper. So, it's not really possible to reason generically about how to handle the entrypoints.

**Comment by NathanielHill** [comment]
I've suggested absorbing the template `server.js` and `client.js` into Sapper as default behavior in the case of their absence. This probably covers the vast majority of users (at least for `server.js`) and might make a serverless build more approachable?

**Comment by Rich-Harris** [comment]
I had wondered about that, yeah. I don't have a good sense of how we'd handle things like authentication in that case. It's possible that we need to think a bit more atomically.

**Comment by NathanielHill** [comment]
> I had wondered about that, yeah. I don't have a good sense of how we'd handle things like authentication in that case. It's possible that we need to think a bit more atomically.

Yeah, this is definitely an issue. I would do something like write a shared authentication module which you can then wrap each page in.

**Comment by NathanielHill** [comment]
But, there would certainly be an escape hatch by simply using a custom `server.js` and just using the `@now/node` builder. I think it would be great to get a simple serverless builder that can generate lambdas for each route, and then go from there.

Although I know when we discussed this before, you were opposed to absorbing `server.js` since you would then need to add polka/express etc as Sapper dependencies. Have you thought about this any more?

**Comment by Rich-Harris** [comment]
> Have you thought about this any more?

A little. There's a PR (from May, which tells you everything you need to know about how much time we've had to focus on Sapper lately 😬) that removes any dependencies from `server.js` except Sapper itself:

```js
// server.js
import * as sapper from '@sapper/server';

sapper.start();
```

It does this by using [sirv](https://github.com/lukeed/sirv) internally for handling static assets, and just using Node's built-in http module rather than expecting you to bring a framework like Polka or Express.

**Comment by NathanielHill** [comment]
> It does this by using [sirv](https://github.com/lukeed/sirv) internally for handling static assets, and just using Node's built-in http module rather than expecting you to bring a framework like Polka or Express.

That sounds great. Yeah the default case is so simple that the `http` module itself should do the trick.

**Comment by msweeneydev** [comment]
Hello @antony, @NathanielHill, @matt3224, @konsumer, @rof20004, @Rich-Harris -  I'm pleased to say that today we've optimized Sapper for Now and added an [example](https://github.com/zeit/now-examples/tree/master/sapper) that uses `sapper export` 🎉

**Comment by rof20004** [comment]
@msweeneydev The sky is shinning :)

Thanks to all that made this happens!

**Comment by antony** [comment]
@msweeneydev looks excellent - thanks for your hard work! Does this mean I can expect *non* exported Sapper applications to work as well now?

**Comment by controversial** [comment]
@msweeneydev My understanding is that it was already possible to serve static sites using Now with `sapper export`, what's changed? It seems like it's still not possible to use Now as a serverless host for Sapper apps.

**Comment by Conduitry** [comment]
Closing this because the process for serving a completely static exported site has been streamlined seems entirely incorrect.

**Comment by msweeneydev** [comment]
@Conduitry, a Sapper example has now been provided and as a result the issue closed.

I do however, understand that what the Sapper community really wants is the ability to deploy all types of Sapper apps, not just those that are statically exported. When Sapper is able to support the generation of serverless functions, this is something we can look to get done.

As a result, I will create a new issue, referencing this one, that specifies exactly what is required.

**Comment by dmitrykurmanov** [comment]
Is it work only with the Webpack `sveltejs/sapper-template#webpack` ? Does it work with the Rollup `sveltejs/sapper-template#rollup` too?

**Comment by antony** [comment]
@dmitrykurmanov it's just exporting a static site, so it bears no relation to Sapper or rollup or webpack whatsoever.
