### ISSUE TITLE
V2 site issue: Node/Express deploying but only displaying directory.

### ISSUE THREAD

**Issue by TheoMer** [zeit/now-examples#199]
So my site id being deploying using the following configuration:

```
{
    "version": 2,
    "builds": [
        { "src": "package.json", "use": "@now/node-server" }
    ],
    "routes": [
        { "src": "/src", "dest": "/index.js" }
    ]
}
```

but when the site ( https://backend-4isc1bhmw.now.sh/ ) is visited only a directory listing is displayed. What am I overlooking here? (See attached image of package.json and directory structure)

![now setup issue](https://user-images.githubusercontent.com/15969262/50184938-5e6ae500-030e-11e9-85a9-545199017895.jpg)

**Comment by rauchg** [comment]
`src` needs to target the JavaScript file that starts up the server. I recommend something like `index.js` if your intent is to serve `/` requests to it.

Check out our example: https://github.com/zeit/now-examples/blob/master/nodejs-express/now.json#L5

**Comment by paulogdm** [comment]
Hello!

Because of your routing:
```
    "routes": [
        { "src": "/src", "dest": "/index.js" }
    ]
```
Only `/src` is acessible. Maybe you want something like the following?
```
    "routes": [
        { "src": "/(.*)", "dest": "/index.js" }
    ]
```
