### ISSUE TITLE
How to use Python 2.7 for the deployment ?

### ISSUE THREAD

**Issue by nirmalrizal** [zeit/now-examples#206]
I have code written on Python 2.7 but the deployment is based on Python 3. Can anyone provide any solution for deploying Python 2.7 code ?

**Comment by nirmalrizal** [comment]
I have tried using "@now/python@2" on the configuration but it didn't worked.

**Comment by paulogdm** [comment]
Sorry for the delay @nirmalrizal !
We have plans for you to customize the environment, including the ability to choose python versions. Please, stay tuned for the release of this feature.

**Comment by nirmalrizal** [comment]
Okay. Thank you
