### ISSUE TITLE
nodejs-koa-ts example not working

### ISSUE THREAD

**Issue by samuela** [zeit/now-examples#221]
I just ran `now init`, selected nodejs-koa-ts, and then:
```
$ now
> Deploying ~/dev/zeit-test under samuela
> Synced 3 files (21.92KB) [1s]
> https://zeit-test-iyphl8l54.now.sh [v2] [in clipboard] [916ms]
╶ src/routes/default.ts        Building            
╶ src/routes/second.ts         Error               [14s]
╶ src/routes/first.ts          Error               [14s]
> Error! 2 build failures occured.
> Error! Check your logs at https://zeit-test-iyphl8l54.now.sh/_logs or run `now logs zeit-test-iyphl8l54.now.sh`.
```

Looks like it's tripping over typescript syntax.

**Comment by timothyis** [comment]
Thanks for pointing this out @samuela, we'll take a look

**Comment by samuela** [comment]
Using `@now/node@canary` instead of `@now/node` works.

**Comment by paulogdm** [comment]
That was my mistake @samuela ! Sorry!

**Comment by samuela** [comment]
Thanks for addressing! No worries!

**Comment by samuela** [comment]
Is there a timeline for getting TS support into `@now/node`?

**Comment by paulogdm** [comment]
It should land in a few days @samuela .
Also, maybe we should add a build entry in the monorepo for `nodejs-koa-ts` @timothyis ?
This way we can know when it fails!

**Comment by paulogdm** [comment]
This is now resolved.
