### ISSUE TITLE
Apollo example does not work

### ISSUE THREAD

**Issue by steida** [zeit/now-examples#239]
I tried to run Apollo example but without success.

I tried my default `/api` code and it worked.

My code uses apollo-server:

```ts
import { ApolloServer, gql } from 'apollo-server';

const server = new ApolloServer({
  context: async ({ req }: { req: IncomingMessage }): Promise<Context> => {
    const user = await getUser(req);
    const models = createModels(db, user);
    return { models };
  },
  // Enforce introspection and playground for production.
  introspection: true,
  playground: true,
  // @ts-ignore Wrong types.
  resolvers,
  typeDefs: gql`
    ${importSchema(__dirname + '/schema.graphql')}
  `,
});

server.listen().then(({ url }: { url: string }) => {
  // tslint:disable-next-line:no-console
  console.log(`Server ready at ${url}`);
});
```

I don't know why example uses `express` and why it does not work. But this example works for me.
Maybe it helps someone.

**Comment by timothyis** [comment]
Hi @steida, I just tried to deploy the Apollo example from this repository with success: https://apollo-2d000zsne.now.sh/graphql
Can you see any errors in the logs of your deployment? Does it fail to build or error when loading?

**Comment by steida** [comment]
Then it was probably some error on my side.

I simplified example and it works.

https://github.com/zeit/now-examples/pull/240

**Comment by konsumer** [comment]
I am getting an unspecified error, when I just run `now` in apollo dir.

```
> Deploying ~/Downloads/now-examples-master/apollo under konsumer
> Using project apollo
> https://apollo-iwuehx99k.now.sh [v2] [in clipboard] [1s]
╶ index.js        Error               [2s]
> Error! 1 build failure occured.
> Error! Check your logs at https://apollo-iwuehx99k.now.sh/_logs or run `now logs apollo-iwuehx99k.now.sh`.
```

When I look at that url, I get no logs:
<img width="553" alt="screen shot 2019-01-30 at 6 44 28 pm" src="https://user-images.githubusercontent.com/83857/52027158-36e76a80-24bf-11e9-8d53-2915e6c2b7fc.png">

**Comment by timothyis** [comment]
Hi @konsumer, we're currently trying to work with AWS to restore service to our functions: https://twitter.com/zeit_status/status/1090786963932688384

**Comment by paulogdm** [comment]
This is now resolved!
Sorry for the trouble people.
