### ISSUE TITLE
Add Hugo demo

### ISSUE THREAD

**Issue by dremonkey** [zeit/now-examples#24]
Not sure who can help me here with this but would love to get this [hugo + now example](https://github.com/dremonkey/hugo-nowjs-example) added to this repo. What would the process for this be?

**Comment by TooTallNate** [comment]
Hey there @dremonkey! Perhaps give something like https://github.com/publysher/docker-hugo a try. We'll get an example set up in this repo as an example, or we'll accept a pull request if you beat us to it.

**Comment by TooTallNate** [comment]
Yup, just open a PR. I'll take a look.
