### ISSUE TITLE
Add multiple Next.js apps monorepo example

### ISSUE THREAD

**Issue by fillipvt** [zeit/now-examples#242]
I'm currently doing [a monorepo](https://github.com/fillipvt/portfolio), it currently has 2 Next.js apps:

- One statically rendered - the blog
- One with a serverless target - the main app

One of the problems I've found with this is that the prefetch feature from `<Link/>` doesn't work between apps. [Here's the issue](https://spectrum.chat/?t=df2363be-a9da-4644-b671-dd7718a6092e) explaining it.

So this issue is to try to get an example of the recommended way to implement multiple apps using Now 2.0

One question that this would solve is: 
- Is `multi-zone` necessary/recommended? If yes, how would that work?

Thanks for reading

**Comment by andresggarcia** [comment]
+1 Trying to do the exact same thing right now.

**Comment by timothyis** [comment]
Thanks for the suggestion. We'll look into this!

**Comment by fillipvt** [comment]
Thanks for looking into this @timothyis !

The other problem we've faced with this type of monorepo is sharing components/code between two or more NextJS apps.

What we've tried consists of:

- `next-plugin-transpile-modules`
- Yarn Workspaces

But this does not work when deploying to Now 2.0. The only thing working so far is to publish an npm package to the registry and then use that so that Now 2.0 is able to pull every needed component/code during the build process. This and more approaches are currently being discussed in a big [thread here](https://spectrum.chat/?t=b33eb62b-7399-4e48-8f31-27117e07ea76).

**I think publishing npm packages just for a handful of components would be a bit overkill.**

So another question this example **could** solve would definitely be **how to share code/components between NextJS apps inside the Now 2.0 serverless environment**.

I believe a lot of people would highly appreciate and benefit from an example that also covers this. Please consider it! :)

**Comment by dav-is** [comment]
@fillipvt I've just published a change to `@now/next` that should allow for what you're asking for.

I appreciate it if you could try it out and follow back up in this issue with the results :raised_hands: 

You can do so with a `now.json` similar to this:
```
{
    "version": 2,
    "builds": [
        { "src": "www/package.json", "use": "@now/next@canary" }
    ]
}
```

**Comment by fillipvt** [comment]
Hey @dav-is 

I'm glad to report that it is now working! The `shared-component` folder is being correctly uploaded and then transpiled with the help of `next-transpile-modules`

I'd like to propose the recent work I've done in [portfolio](https://github.com/fillipvt/portfolio) as an example to showcase the current state of monorepos in Now 2.0. If there's need for a simpler example I can work on it.

Here's the deployment [fillipvt.com](fillipvt.com), the "header component" is being shared across the main app (home page) and blog.

It's looking pretty great! This is I believe is a really great step forward. Tyvm for your work.

**Comment by msweeneydev** [comment]
Closing as the issue has now been resolved.
