### ISSUE TITLE
How to deploy NextJS CRA with HTTPS/SSL

### ISSUE THREAD

**Issue by ScottAgirs** [zeit/now-examples#254]
Successfully deployed GraphQL Yoga server with `https` cert options to https://localhost:4444, however, not able to figure out how to deploy Create-React-App to now with SSL.

Thanks

**PS.**
This is needed for me to develop Facebook OAuth in development environment

**Comment by timothyis** [comment]
Hi @ScottAgirs. All deployments with Now should automatically have an SSL certificate assigned. Could you send me a deployment URL (feel free to email it to me timothy at zeit.co) where you're not seeing SSL for your CRA deployment?

**Comment by ScottAgirs** [comment]
@timothyis thank you for your reply and sorry about this.

I managed to find the issue, which was not related to next, but my local configs, will not dive into explaining, as this is my case specific, would be lengthy, and is still work in progress.. :) 

thanks again
