### ISSUE TITLE
my now.json not able deploy.

### ISSUE THREAD

**Issue by AnthonyLaw** [zeit/now-examples#269]
i'm not able deploy.

```
{
    "version": 2,
    "name": "project",
    "builds": [
        { "src": "./bin/www", "use": "@now/node-serve" },
        { "src": "*.js", "use": "@now/node" }
    ],
    "routes": [
        { "src": "/", "dest": "/routes/index.js" },
        { "src": "/ab", "dest": "/routes/ab.js" }
    ]
}
```

**Comment by timothyis** [comment]
Hi @AnthonyLaw, `@now/node-serve` is not a valid Builder. I believe you're looking to use `@now/node-server`. Please try that instead! Although, also look into using [@now/node](https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node) for added benefits.
