### ISSUE TITLE
GitHub Integration Issues

### ISSUE THREAD

**Issue by ahikmatf** [zeit/now-examples#289]
Recently I signup for an account, and connect it with my GitHub, then I want to create a project from a sample provided, but got an error.

![image](https://user-images.githubusercontent.com/9145032/53688800-12abd180-3d7c-11e9-9f39-0a3569bcae7e.png)

Here's I think how to reproduce the error:
1. Open `zeit.co` and click Join Free
2. Continue with GitHub
3. Authorization thing...
4. I choose repository access only for one specific repository
5. Continue to `zeit.co/now` process
6. Create project from template
7. Error like the above picture

And this how I try to solve the problem
1. I click the link, change to all repositories
2. Back to that `zeit.co/new` tab, still got the error
3. Refresh, got same error
4. Opening the link in new tab, the error is still exist
5. Login using incognito mode (prevent some cache maybe), still the same

Did I miss something?
Thank you

**Comment by MAPESO** [comment]
@ahikmatf Hi 👋, What was the template you choose ?

**Comment by ahikmatf** [comment]
its `gatsby` and `vue`, but I think on all them (?) @MAPESO

**Comment by quietshu** [comment]
Hi @ahikmatf, did you create a new team in the onboarding process? 

If so, the GitHub integration might be installed into your team account. You can select your team on `zeit.co/new`: 
![image](https://user-images.githubusercontent.com/3676859/53690567-210fe280-3da8-11e9-832a-313f1c4fa65d.png)

**Comment by ahikmatf** [comment]
It's on my personal account.

But it solved now, I uninstall and re-install the Now app on my GitHub 😕 Maybe I did something wrong or skip something in on boarding process...

**Comment by adamgranted** [comment]
Ran into the exact same issue, I had to remove Now from Github and re-install.

**Comment by hyusetiawan** [comment]
im facing the same issue as well

**Comment by arunoda** [comment]
@hyusetiawan I saw you have connected your account to a team.
But you can connect it your ZEIT user account as well.
You can click the following link and remove it from GH.
<img width="782" alt="Screen Shot 2019-11-15 at 11 11 46 AM" src="https://user-images.githubusercontent.com/50838/68919661-e9f82a80-0798-11ea-992e-6a7d94dd01c1.png">

Then simply connect that to your user account.

If you still having this issue, drop us an email to: support@zeit.co
