### ISSUE TITLE
Further explanation of the 'name' field in now.json

### ISSUE THREAD

**Issue by msweeneydev** [zeit/now-examples#292]
Currently, the text 'We will also define a name for our project (optional)' is present on all examples with the exception of Apollo Server and docz. The docz example has a link to the 'name' documentation but there is no mention for Apollo Server. (Editing these to be consistent with the majority of examples should be a seperate issue)

In my opinion, this needs further clarification. The benefit of including the 'name' field is ambiguous because of this but could be resolved by including a link to the documentation that further explains it [here](https://zeit.co/docs/v2/deployments/configuration#name).

I am proposing that any time now.json is referenced, we use a template that provides a short explanation of each field being used, together with a link to the documentation for it. Whilst at the bottom of each now.json example there is a link to the full documentation, including field links when they are initially mentioned would improve clarity and help users find relevant information quicker.

**Comment by brymut** [comment]
Hey @msweeneydev @timothyis , I'd be more than happy to have a go at this for you if no one's currently on it. Is that alright with you?

**Comment by msweeneydev** [comment]
Hey @brymut, that would be great, thank you!

**Comment by msweeneydev** [comment]
Closing this issue as we are now documenting `now.json` fields.
