### ISSUE TITLE
Cannot run rust-scraper locally

### ISSUE THREAD

**Issue by merelinguist** [zeit/now-examples#309]
The rust-scraper example doesn’t work locally because there is no main function defined. Is there any way to fix this?

**Comment by anmonteiro** [comment]
@merelinguist thanks for your interest in `@now/rust`. We plan on adding Rust support to `now dev` such that this is more tightly integrated, but for now I can see 2 alternatives:

1. you make your handler public with the `pub` keyword (e.g. `pub fn handler(...`) and test it out from some other Rust file.

2. You use the `Cargo.toml` entrypoint (documented [here](https://zeit.co/docs/v2/deployments/official-builders/now-rust/#cargo.toml-entry-point)) and set up your local testing according to whether you're in a (Now v2) lambda environment or a local one.

**Comment by merelinguist** [comment]
@anmonteiro Thanks for the speedy response! Excited to build some amazing things with rust. 🤸‍♂️

**Comment by unicodeveloper** [comment]
Glad that you got this resolved @merelinguist. Closing this issue now.
