### ISSUE TITLE
Github integration doesn't know the redirect example works

### ISSUE THREAD

**Issue by giraffesyo** [zeit/now-examples#313]
I followed the example at https://github.com/zeit/now-examples/tree/master/redirect

The example worked perfectly, allowing me to redirect.

I later noticed that I received this comment on my repo:

![comment](https://puu.sh/CYU9m/a48cad97f4.png)

It seems like the GitHub integration isn't aware that this example is actually possible, despite it working just fine by using the cli.

**Comment by timothyis** [comment]
We're working on this. Thank you for letting us know.
