### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by flawyte** [zeit/now-examples#336]
The syntax highlighting for the `now.json` file in the [Monorepo example](https://zeit.co/examples/monorepo/) (at the very bottom) is broken :

![image](https://user-images.githubusercontent.com/1585006/55817780-82d51200-5af5-11e9-8769-98ba8ed29753.png)

**Comment by msweeneydev** [comment]
Hey @flawyte, thank you for reporting this. In order to simplify things for customers we've now made this repository the sole place you can view examples. As a side effect, this issue no longer occurs.
