### ISSUE TITLE
Apollo Example not detecting updates when using Now dev 

### ISSUE THREAD

**Issue by captDaylight** [zeit/now-examples#346]
When I run the Apollo example with `now dev` and have say a request like:

```
curl \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{ "query": "{ book(id: 1) { title } }" }' \
  http://localhost:3000
```
everything works as expected:
```
{"data":{"book":{"title":"The Trials of Brother Jero"}}}
```
However if I change the title of the book in `index.js` and run the command again I'm getting the exact same result.

**Comment by msweeneydev** [comment]
Hey @captDaylight, I'm closing this issue as the example is no longer part of the repository. We have a guide on this however: https://zeit.co/guides/deploying-apolloserver-to-now/

Please feel free to open another issue in the [docs repository](https://github.com/zeit/docs) if you feel this is unresolved.

**Comment by chhuang** [comment]
@msweeneydev do you know why it was removed?

**Comment by msweeneydev** [comment]
Hey @chhuang, the majority of examples were removed so we could start again with a solid base and clearer direction. As you might have seen, this repository now focuses on a static front end, with a few examples of how to add a serverless function.

This is based on what users have told us, it's much easier to start your project using the `now init` command now than ever before, a starter Gatsby, Next or Hexo app for example provides more value early on than just a standalone Node.js function.

This repository will likely be expanded in the future, using a similar pattern to provide more value to users but going into greater detail with real use cases, things like authentication, using databases etc.
