### ISSUE TITLE
.nowignore files

### ISSUE THREAD

**Issue by vpicone** [zeit/now-examples#360]
Some of the examples are missing `.nowignore` files. Gatsby for instance. `node_modules` and `public` should for sure be ignored but what about `.cache/`?

**Comment by timothyis** [comment]
Good question! `.cache` should definitely be ignored for Gatsby. Please feel free to contribute this!

**Comment by antonmoiseev** [comment]
Isn’t it inherited from `.gitignore`? The Gatsby example has `node_modules`, `.cache` and `public` in the `.gitignore`.

**Comment by jaydenseric** [comment]
There are also some redundant `.nowignore` entries, see https://github.com/zeit/now-examples/pull/369#issuecomment-492495525

@vpicone it seems you don't need to ignore `node_modules`: https://github.com/zeit/docs/issues/767

**Comment by vpicone** [comment]
Interesting, looks like we'd still need `.cache` and `public`. I've been holding off because I'm not sure if `.gitignore` should suffice or if folks should be more explicit? 

Seems like there's a mix of answers to that in the examples.

**Comment by msweeneydev** [comment]
Hey @vpicone, this has been fixed with #423 - thank you for letting us know!

We'll be updated the documentation very shortly to list which files are ignored by default with `.nowignore`.
