### ISSUE TITLE
Handling overlimit in nextjs-mysql example

### ISSUE THREAD

**Issue by prKassad** [zeit/now-examples#363]
A large (or negative) limit can not be parsed MySQL in nextjs-mysql example.
For example, [URL /api/profiles?page=0&limit=99999999999999999999](https://nextjs-mysql.now.sh/api/profiles?page=0&limit=99999999999999999999) return:
`{"profiles":{"error":{"code":"ER_PARSE_ERROR","errno":1064,"sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '100000000000000000000' at line 2","sqlState":"42000","index":0,"sql":"\n      SELECT *\n      FROM profiles\n      LIMIT 0, 100000000000000000000\n    "}},"pageCount":1,"page":1}`

**Comment by timothyis** [comment]
Good catch! We will be releasing a fresh version of the mysql example this week with this fixed. Please feel free to contribute a fix for the current in the meantime, though!
