### ISSUE TITLE
can't access build/dist folder

### ISSUE THREAD

**Issue by jmonster** [zeit/now-examples#364]
Context: I am attempting to use Ember Fast Boot; I otherwise have no problems deploying my ember project as a typical static site.

---

By default, everything expects the output folder to be `dist`. Since that didn't work I went ahead and explicitly specified `./diss`. This has clarified that my code's local `diss` is different from Now's built folder of the same name.

I logged out node's `process.env` but didn't see any hints how I might find that temp folder. I've tried explicitly setting an absolute path -- `/tmp/diss` -- but it fails due to permissions. So, **how do I retrieve the tmp folder where my built project is from my script's runtime?**

### runtime error
```
2019-05-06T08:21:09.726Z  Built project successfully. Stored in "/tmp/3704f3e5/diss".
...a list of files successfully built...
2019-05-06T08:21:47.621Z  Error: Couldn't find /var/task/diss/package.json. You may need to update your version of ember-cli-fastboot.
                              at EmberApp.readPackageJSON (/var/task/fastboot.js:11541:13)
```

### now.json (snippet)
```json
{ "src": "package.json", "use": "@now/static-build", "config": { "distDir": "./diss" } },
```

### package.json (snippet)
```
"now-build": "ember build --environment=production --output-path=./diss",
```

### fastboot.js (complete)
```js
const express = require('express');
const fastbootMiddleware = require('fastboot-express-middleware');

const app = express();
app.get('/*', fastbootMiddleware('./diss')); // this should be /tmp/3704f3e5/diss

module.exports = app;
```

### when attempting to use /tmp/diss
```
2019-05-06T08:39:51.406Z  Built project successfully. Stored in "/tmp/diss".
# ..various successful messages..
Error: Build was unable to create the distDir: diss.
  Make sure you mentioned the correct dist directory: https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build/#configuring-the-build-output-directory
```

**Comment by paulogdm** [comment]
Here is how `@now/static` builder works:  It will take everything on the folder `diss` and make it the new "root" of your build. Therefore your source is not present after the build process.
Try: `app.get('/*', fastbootMiddleware(__dirname + '/diss'));`

Also, are you sure you want to run Express in a serverless environment? I mean, are you building a monolithic app in Now 2.0? (That is certainly not recommended).

**Comment by jmonster** [comment]
I’m exporting the req/res callback rather than starting a server listening on a port. I think that’s the intended strategy from Now’s docs? Unfortunately there’s not much useful information on Fastboot out there so I’m stabbing in the dark a bit as I figure out the Now service itself simultaneously. Does that make sense or is this still not the desired approach?

Thanks so much for your response, I’ll see if that gets me any closer to success!

**Comment by paulogdm** [comment]
`@now/static-build` is aimed for things like `create-react-app`, Gatsby or Next.js static. So you may be looking for `@now/node-server`.
Is your code public somewhere?

**Comment by jmonster** [comment]
I went ahead and made it public for now; my `now.json` is @ https://github.com/jmonster/dohnnysdiscountgas/blob/master/now.json

I've been making a lot of different attempts, the latest was using now/static to compile the app (easy AF) and then use now/node to serve the output of it *using Fastboot which pre-renders the page*. Can you suggest a better way? I'm about to try the `__dirname` suggestion

**Comment by paulogdm** [comment]
From the [fastboot](https://github.com/ember-fastboot/ember-cli-fastboot) repository, I can see that this may not be a good approach. A specialized builder, like `@now/next` or `@nuxtjs/now-builder`, should be the way to make this deployable with [now.sh](now.sh).
Even if you make this work with Express it would become a bigger and bigger lambda as you add pages. Hurting the performance of all pages. We discuss that [here](https://zeit.co/blog/customizable-lambda-sizes#the-lambda-execution-model).
