### ISSUE TITLE
puppeteer with serverless lambda

### ISSUE THREAD

**Issue by bala1074** [zeit/now-examples#370]
I am trying to run puppeteer on aws lambda, i have followed the zeit exmaple for capture screenshot. But right now, i am using serverless.yml with lambda function. so, how to set the config which is mentioned in now.json for lambda. I miss the now.json confing, and when I try to deploy serverless, it took almost 1min time and after deployment when I trigger lambda function returns error related to size.

**Comment by msweeneydev** [comment]
Hey @bala1074, I'm sorry to hear you're having difficulty with this. As you might have seen, the Puppeteer is no longer part of this repository. However, if you are looking for the previous example, you can find it [here](https://github.com/zeit/now-examples/blob/a28ecde674fea304f079d1200b04eed502733973/puppeteer-screenshot/now.json).
