### ISSUE TITLE
flaskex local build and postgresql elementsql documentation

### ISSUE THREAD

**Issue by headwinds** [zeit/now-examples#392]
I want to provide some documentation for deploying the [flaskex sample](https://github.com/zeit/now-examples/tree/master/flaskex-postgresql) with [elephantsql](https://www.elephantsql.com) which provides a nice free tier hosted postgresql database for hobbyists.

I had to add psycopg2 to the requirements.txt file 

```
Flask==1.0.2
WTForms==2.2.1
SQLAlchemy==1.3.3
bcrypt==3.1.6
requests==2.21.0
pg8000==1.13.1
psycopg2==2.7.7
```

I had to change db secret to:

```
now secret add flashex-db-uri 'postgresql+psycopg2://username:password@dbhost:dbport/dbname'
```

That's it - `now ` to deploy - only took me 2 hours to sort out - so should save you time!

**Comment by headwinds** [comment]
@anfederico perhaps I can create a wiki page on your repo for this or add it to your readme?

**Comment by headwinds** [comment]
@styfle how do you run this example locally?! I had no problem deploying it but how would it work locally if each route is its own flask app? 

I looked at the [original flaskex](https://github.com/anfederico/Flaskex) project all the routes are included in the app.py

**Comment by headwinds** [comment]
Ok I think I got it - I followed this [guide](https://zeit.co/docs/v2/development/basics/) to run `now dev`

**Comment by styfle** [comment]
Hi @headwinds 

The current example is using a PostgreSQL hosted through Amazon but you could use any provider as you mentioned.

I'm not sure why you need to change the db driver in requirements.txt but you can utilize whichever one you prefer. That's why we decided to set the secret to the entire connection string, so this example will work with other drivers as you found.

Our examples typically don't include instructions for setting up databases because we have a https://zeit.co/guides page that is more appropriate for these types of walkthrough guides that require more images.

Would you like to submit a guide for using elephantsql?

**Comment by headwinds** [comment]
@styfle thanks for the advice - I'm basically learning python so most of my decisions are based on what other sites have recommended.  I simply found more sites suggesting that I use the psycopg2-binary over pg8000 but would like to do more research and learn the differences. 

I really liked your example - thought it was super powerful - it had that wow effect when I deployed it - but I'm new to the whole lamdba approach running individual flask apps - and got bogged down trying to run `now dev` - for me it didn't work in my environment and actually it complained about psycopg2-binary. 

So I setup my own [repo](https://github.com/headwinds/flask-now-postgres-offline) which is a bridge between Flaskex and this project so I could learn the more traditional single app approach and then when I feel more confident I may tackle this strategy again. 

I'll consider submitting a elephantsql guide - it arguably more easier to setup than Amazon for a beginner.

**Comment by styfle** [comment]
> thanks for the advice - I'm basically learning python

Amazing, great job so far 🤩

> it arguably more easier to setup than Amazon for a beginner.

Agreed. Another thing to consider when choosing a database for production purposes is [regions](https://zeit.co/docs/v2/platform/regions-and-providers) and replication. For starting out, you could make sure that you deployment is pinned to the same region as your database. As your traffic increases and you need to support a global customer base, you could find a DB provider that does replication to multiple regions.

That being said, I'm glad you liked the example!

Some further reading material if you are interested:

- [now dev blog post](https://zeit.co/blog/now-dev) - some history here
- [python wsgi blog post](https://zeit.co/blog/python-wsgi) - some details here about upgrading existing python apps
- [a bug fix](https://github.com/zeit/now-builders/issues/545#issuecomment-501994688) - consider using `@now/python@canary` until this fix gets shipped to stable

**Comment by headwinds** [comment]
@styfle Yes I looked into the regions docs while developing - I made the decision delete the regions prop from my now.json was based on what I read but I'm probably wrong - I deleted it because I'm in Toronto and if I understand the prop correctly, if I delete it will sort things out for me automagically without me having to think about it. Is that right?

**Comment by styfle** [comment]
If you exclude regions from your `now.json` file then the region closest to you will be used. However, you should use the region closest to your database.

**Comment by headwinds** [comment]
@styfle ahhhh I see now - so I need to find out where ElementSQL has hosted the postgres db and ideally use a region nearest to it - makes sense - thanks!
