### ISSUE TITLE
improvements on `nextjs-static` example (nextjs 9)

### ISSUE THREAD

**Issue by balazs4** [zeit/now-examples#419]
### Current behaviour: :x: 

<https://nextjs-static-9-broken.now.sh/about> returns with 404 when you open it with direct link.
If you open the <https://nextjs-static-9-broken.now.sh/> and click on the `about` link it works as expected.

### Solution :heavy_check_mark: 

add `exportTrailingSlash: true` to the `next.config.js`

````js
// next.config.js
module.exports = {
  exportTrailingSlash: true
};
````

Result: <https://nextjs-static-9-fixed.now.sh/about>

More details: <https://nextjs.org/docs#static-html-export>

**Comment by balazs4** [comment]
@timneutkens @leo @rauchg is it possible do the something similar without touching `next.config.js` file?
for example with `routes` in `now.json`?   :thinking: 

````json
"routes": [
  { "src": "/(.*)", "dest": "/$1.html" }
]
````

`@now/static-build` could add some 'silent' redirection to the `now` deployment automatically which matches to the `next@9.x` features.

**Comment by balazs4** [comment]
:tada:  It seems to be working...  https://nextjs-static-6mk4acx38.now.sh/about

````js
// next.config.js
module.exports = {}
````

`now.json` looks like:
````json
{
  "version": 2,
  "name": "nextjs-static",
  "builds": [{ "src": "package.json", "use": "@now/static-build" }],
  "routes": [{ "src": "(.*)", "dest": "$1.html" }]
}
````

any drawback of this solution in the `now`, `nextjs 9.x`, `static export` world?

**Comment by msweeneydev** [comment]
Hey @balazs4, thank you for reporting this. At the time we were completely revamping our examples. As you've probably seen, there is now only one Next.js example. I'd love to get your thoughts on the new examples as well - no more need for either `next.config.js` or `now.json` 🎉

**Comment by rauchg** [comment]
Also @balazs4 to be even more clear, we intelligently export to HTML now thanks to Next.js 9:
https://nextjs.org/blog/next-9#automatic-static-optimization
