### ISSUE TITLE
where are some examples like koa and express gone?

### ISSUE THREAD

**Issue by jjangga0214** [zeit/now-examples#432]
They suddenly(?) disappeared. What happened?

**Comment by jdivy** [comment]
Looks like a bunch got swept up in this commit https://github.com/zeit/now-examples/pull/423/commits/929fb217461b7114adf55f51e55338a2d9876e35 and I don't really get it either...a 6 month old blog post is now irrelevant?  Broken links? https://zeit.co/blog/serverless-express-js-lambdas-with-now-2

**Comment by PaulPCIO** [comment]
Would also be nice to see the examples including now.json

**Comment by varna** [comment]
Maybe they changed something in now-cli, again?
Or maybe this is a prelude for now.js

**Comment by TitusEfferian** [comment]
make yourself familiar how `now.json` configuration works:
https://zeit.co/docs/v2/advanced/configuration

here some `now.json` example to build express application:
```
{
    "version": 2,
    "name": "YOUR_APP_NAME",
    "builds": [
        {
            "src": "**/*.js",
            "use": "@now/node"
        }
    ],
    "regions": [
        "sin1"
    ]
}
```

and here is how `index.js` entrypoint look likes:
```
const express = require('express')
const helmet = require('helmet')
const cors = require('cors')

const app = express()
app.use(helmet())
app.use(cors())

app.get('*',(req,res)=>{
  res.send({
    message:'hello world'
  })
})

module.exports = app
```

**Comment by TitusEfferian** [comment]
any new PR for updated `express` example?

**Comment by fillipvt** [comment]
I'm also curious about this, are the examples coming back?

**Comment by skllcrn** [comment]
We’re optimizing our examples with a focus on full-stack apps using popular frameworks. Our previous examples were unwieldily and too specific in nature. As an example, our customers tend to deploy full apps (like Vue + Node.js functions), instead of just an isolated function.

Take a look at the [new Next.js example](https://github.com/zeit/now-examples), which shows how you can implemented your API using familiar helpers like Express, without needing an additional dependency.

**Comment by timothyis** [comment]
P.S. all `now.json` examples still work, but notice that our new examples are 100% zero-config 🎉 

If you have any requests for full-stack examples that you'd like to see, please let us know.

**Comment by fillipvt** [comment]
@timothyis we honestly would love to see an example of something like [this](https://auth0.com/blog/next-js-authentication-tutorial/) implemented on a serverless environment, if possible

**Comment by rauchg** [comment]
That's super helpful to know @fillipvt – we are helping Auth0 improve that guide as we speak

**Comment by reorx** [comment]
python examples are also gone

**Comment by PaulPCIO** [comment]
> P.S. all `now.json` examples still work, but notice that our new examples are 100% zero-config 🎉
> 
> If you have any requests for full-stack examples that you'd like to see, please let us know.

Yea i i have been playing with this since my last message, really it's a pleasant update 🍾

**Comment by leo** [comment]
Thank you for the reports!

As @skllcrn already said, we're trying to focus heavily on frontends that (optionally) have a serverless function (or more) for dynamic data, as making these easy to deploy is our main goal.

However, you can still use `now init nodejs` (replace "nodejs" with the example) to retrieve any of the old examples, if you need to.

**Comment by jdivy** [comment]
I personally would like to see serverless graphql that's considered the ideal way moving forward on now 2.0.  From what I've read so far this is likely to require "some config" as opposed to "zero-config" (e.g. the monorepo concept?).  This is my first serious look at now.sh hosting and it just feels like I can't be the only one looking for a dead simple example to get going :)

The broken blog post links also kinda stink from a newcomer's perspective for what it's worth.

**Comment by rauchg** [comment]
@jdivy it won't. You can certainly have a function powered by Express that is zero config.

We will fix the links, sorry for that oversight.

**Comment by rauchg** [comment]
As an example, api/graphql.js can just be a Apollo function.

**Comment by tim-phillips** [comment]
The dead simple graphql server example is in this guide: https://zeit.co/guides/deploying-apolloserver-to-now

**Comment by vladejs** [comment]
Is there any example or best practice on authentication? There is a guide using express + passport (twitter) but is old and doesn't cover graphql.

Also, is there a place in zeit which recommends how to use real-time communication in serverless environments? e.g: socket.io?

thanks

**Comment by rauchg** [comment]
@vladejs with the release of our helper methods (https://zeit.co/blog/now-node-helpers), using Express.js is really not necessary (although it should still work, and the old examples should work as well).

With regards to real time communication, we recommend using Pusher or PubNub. We will be working on adding an example of these two very soon :)

**Comment by awb305** [comment]
> That's super helpful to know @fillipvt – we are helping Auth0 improve that guide as we speak

@rauchg I've made a [minimal repo](https://github.com/awb305/Auth0-Nextjs-Serverless) with Nextjs and Auth0 implemented in a serverless environment, which was based off of [Auth0's Nextjs guide](https://auth0.com/blog/next-js-authentication-tutorial/) that @fillipvt mentioned and [Nextjs with Cookie Auth](https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth). I'm looking forward to the guide, and I'm happy to help if you need it!

**Comment by jdivy** [comment]
Thinking further, a relatively vanilla OAuth 2 flow in serverless (as well as one using passport?) would be nice.

**Comment by tsaiDavid** [comment]
@rauchg - Not to rush you all, but just curious - when might we expect to see an updated/improved Auth0 guide?

**Comment by jiangbo2015** [comment]
I make it work
[see the link](https://medium.com/@reactbo/how-to-deploy-express-application-to-now-sh-4f066e6fc33b)

```json
{
"version": 2,
"builds": [
{ "src": "*.js", "use": "@now/node-server" }
],
"routes": [{
"src": "/(.*)",
"dest": "/index.js"
}]
}
```

**Comment by SavedByZero** [comment]
Echoing those who want node/express examples. The documentation is confusing and incomplete on those (no examples of how to call the functions from react or axios, no examples of how to find the data you send — req.body is undefined)

**Comment by jjangga0214** [comment]
@msweeneydev 
I haven't looked around zeit now examples for some while.
Thus I don't know this issue is resolved or not.
So, I think it'd be more helpful for people if you explain (at least shortly) **why** closing an issue.

Is this issue resolved? 
If so, how?
If not, why closing?
Is there a specific reason?

**Comment by msweeneydev** [comment]
Apologies @jjangga0214, this one missed a comment.

The examples here are being moved to the [zeit/now](https://github.com/zeit/now/tree/master/examples) repository. Any requests for examples should be created as issues in that repository and we will handle them there.
