### ISSUE TITLE
Example of using CRA Preset in now.json

### ISSUE THREAD

**Issue by mckernanin** [zeit/now-examples#471]
Is there a way of using the automatic handling of create-react-app projects in a now.json?
Zero conf is great until you have functions that need configuration, env vars, etc.

**Comment by rauchg** [comment]
For clarity, zero config doesn't exclude things like needing env. It primarily refers to not needing to configure a build process and routes.

Can you please tell us a bit more about what you're trying to accomplish?

**Comment by mckernanin** [comment]
@rauchg sure!
So I have a project that has been working just fine with no config, now I needed to add env vars to the API lambda to get it running in now (for dev locally just using .env file).
I created a now.json similar to what I have used in the past for something like this. I didn't even think of trying, but is it possible to have a now.json without any builds or routes, just env section?

**Comment by mckernanin** [comment]
Oh wow, I just tried that and didn't expect it to work 😆 
Amazing work as usual!

![](https://media0.giphy.com/media/V3r8yMPAxQcla/giphy.gif)

**Comment by moxiu-fe** [comment]
1111
