### ISSUE TITLE
create-react-app deployments break after ejecting

### ISSUE THREAD

**Issue by bitjson** [zeit/now-examples#472]
Ejected create-react-app projects are not deploying properly with the zero-configuration system. E.g.:

```sh
npx create-react-app my-app
cd my-app
now # confirm that the deployment works initially

yarn eject
now # broken after ejecting
```

Example before: https://test-now-rbdi78gb2.now.sh
Example after: https://test-now-loblmys87.now.sh

Is there a workaround for this currently? Thanks!

**Comment by leo** [comment]
Thanks for bringing this up! We'll take a look.

**Comment by AndyBitz** [comment]
This has been fixed in https://github.com/zeit/now/pull/2873. As soon as it is on stable it will work out of the box, for now Now CLI canary has to be used.
