### ISSUE TITLE
Missing example for Flask - Python

### ISSUE THREAD

**Issue by aniljaiswal** [zeit/now-examples#477]
The announcement page at [Zeit](https://zeit.co/blog/python-wsgi) points to the link <http://zeit.co/examples/flaskex-postgresql/> but that doesn't exist and redirects to GitHub repo where there's no such example.

Can anyone point me to the correct link?

**Comment by msweeneydev** [comment]
Hello @aniljaiswal, this example was removed in a recent update and is no longer available. We hope to have some more Python examples for you soon!

**Comment by justinmoon** [comment]
Can you share why it was removed? Does the old demo still work?

**Comment by justinmoon** [comment]
Update: I played with the old examples and they're unusable. Basic stuff like Flask's `url_for` doesn't work. And `now dev` is extremely slow. It reinstalls all dependencies for every new route you visit, and reinstalls them every time you edit code.

Look elsewhere for serverless python platform.
