### ISSUE TITLE
now dev doesn't work in CRA+functions

### ISSUE THREAD

**Issue by luisrudge** [zeit/now-examples#492]
I run the command and it does nothing.
```
C:\Users\Luis\code\test> now init create-react-app-functions .
> Success! Initialized "create-react-app-functions" example in ~\code\test.
- To deploy, run `now`.
C:\Users\Luis\code\test> now dev
> Now CLI 16.2.0 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
/ Preparing package.json for build: installing to C:\Users\Luis\code\test
```

**Comment by luisrudge** [comment]
repro:

```
now init create-react-app-functions cra-fun
cd cra-fun
npm i
now dev
```

**Comment by msweeneydev** [comment]
Hello @luisrudge, I'm sorry this isn't working for you. I've tried to reproduce with the steps you've provided but it works for me.

A couple of things to consider, CRA will start and open a development server (this will not work with Serverless Functions) automatically, shortly beneath that in the CLI, the `now dev` server will be listed (port 3000 unless in use). The Go Serverless Function takes a little while to build the first time whilst in development.

Could you provide me with the issue you are facing so I can try to resolve them for you?

**Comment by williamli** [comment]
FYI: https://twitter.com/_wli/status/1172423741457883138

I am filing an issue on this.

**Comment by williamli** [comment]
https://github.com/zeit/now-examples/issues/493

**Comment by luisrudge** [comment]
Yup, I'll close this one in favor of #493. If I manually open localhost:3000, then it works.
