### ISSUE TITLE
meteor example: rate limit error

### ISSUE THREAD

**Issue by roelvan** [zeit/now-examples#54]
It is trying to upload all local files which in turn throws a rate limit error. Especially for larger projects...
```
Error! An unexpected error occurred in deploy: Error: Rate limit exceeded (429)
    at responseError (/snapshot/repo/dist/now.js:2561:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by joecohens** [comment]
Thank you so much for the effort you have put into this issue! 😊

We are closing it for now since it is not applicable to our newest release Now 2.0.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
