### ISSUE TITLE
node react v2 example code?

### ISSUE THREAD

**Issue by nickbouton** [zeit/now-examples#58]
Hi - I'm looking for the example source for the [`node-react`](https://node-react-v2.now.sh/) example listed in the [`README.md`](https://node-react-v2.now.sh/), to test out with your new serverless Docker beta.

Has that been published to the repo yet or is the readme out of sync?

**Comment by TooTallNate** [comment]
Hey there Nick. That example was renamed to `static-react` in  70948f4640c09671bc24bff75194f6bf3a0ef301. Thanks for pointing out that the readme needs to be updated.

**Comment by nickbouton** [comment]
Thanks @TooTallNate - appreciate the quick response!
