### ISSUE TITLE
[php-wordpress]: Add more containers

### ISSUE THREAD

**Issue by cr101** [zeit/now-examples#68]
I've been using [wp-local-docker](https://github.com/10up/wp-local-docker) which is great.

Please consider also adding elasticsearch, memcached, mailcatcher, mysql, phpMyAdmin and phpMemcachedAdmin to the php-wordpress example.

**Comment by joecohens** [comment]
Thank you so much for the effort you have put into this issue! 😊

We are closing it for now since it is not applicable to our newest release Now 2.0.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
