### ISSUE TITLE
Needs Apollo GraphQL example

### ISSUE THREAD

**Issue by matheuss** [zeit/now-examples#69]

**Comment by lukeburns** [comment]
Is there a reason that the Apollo example uses @now/node-server rather than @now/node, which seems to be the recommended approach? Trying to make a decision on how to use GraphQL with Now v2.

**Comment by rauchg** [comment]
Apollo exposes a server interface, not a callback. If they had an API for exposing a function handler, like `koa` does (`koa.callback`), you could use `@now/node`.

**Comment by rauchg** [comment]
Also, this is now done. Thanks for the reminder @lukeburns

**Comment by rauchg** [comment]
Either way @lukeburns, it's worth pointing out that no matter whether you use `@now/node` and `@now/node-server`, you are still building a "monolithic" function. It's better to focus on solutions that allow you to split out your backend into multiple entrypoints, to avoid towering complexity.

**Comment by lukeburns** [comment]
@rauchg, sure thing.

`apollo-server-micro` exposes a handler for `micro`, rather than a server interface. Got this running locally with `micro` but doesn't seem to play well with `@now/node`: https://apollo-plv2vr8fl.now.sh/_src. Any ideas on why this might be? ([source](https://github.com/lukeburns/now-examples/tree/master/apollo))

The `express-graphql` handler seems to work fine with `@now/node`: https://graphql-http-mg0bqia77.now.sh/_src. ([source](https://github.com/lukeburns/now-examples/tree/master/graphql-http))

Do you have thoughts on handling splitting for graphql services? The purpose of GraphQL is pretty much to combine multiple endpoints into one. Is there a smart way of composing lambdas, so that resolvers can be broken out into separate lambdas, while still being called from a single endpoint, without a lot of overhead?

**Comment by rauchg** [comment]
> Do you have thoughts on handling splitting for graphql services? The purpose of GraphQL is pretty much to combine multiple endpoints into one. Is there a smart way of composing lambdas, so that resolvers can be broken out into separate lambdas, while still being called from a single endpoint, without a lot of overhead?

I've been talking with @mxsbtr, @schickling and @pranaygp in passing about this. One idea that might work well is that you split each top-level type into its own function, and the GraphQL entrypoint is in charge of performing the invocations.

That way, there wouldn't be "compounding growth" into the function that receives your GraphQL requests.

I'm not a GraphQL expert but I definitely think it's an interesting space for experimentation.

**Comment by pranaygp** [comment]
Definitely something to solve!

cc @mfix22 who's working on this problem as we speak 😁

**Comment by schickling** [comment]
Very interested in learning more about this. I think it's important to state what we're trying to optimize here or put differently: What's the problem we're trying to solve?

A GraphQL API is typically exposing one (usually fully-connected) schema. Therefore trying to break the query execution into multiple sub-functions might be non-trivial. One idea could be to split across individual `Query` root fields however, I'm not sure whether that's worth the effort. (Another approach could be to deploy individual types/resolver functions separately but I'm pretty sure that's a bad idea bc of the IO overhead.)

I think the far more promising approach would be to make better use of the idea of persisted queries in combination with something like [graphql-jit](https://github.com/ruiaraujo/graphql-jit).

@rauchg can you elaborate a bit more on the expressed goal here / problem we're trying to solve by splitting up the schema query execution?

**Comment by BassT** [comment]
Maybe it makes sense to look at this issue not only from a schema or endpoint perspective.

As far as I understand, as a developer I need to make sure my bundle size stays small (< 5MB) in order to benefit from the serverless nature of Now v2.

So, as long as the bundle size of my GraphQL API is small I don't need to worry about splitting my resolvers because the whole API will scale nicely.

Once I implement a resolver that requires a larger dependency (e.g. [jsdom](https://bundlephobia.com/result?p=jsdom@13.1.0)) I deploy this resolver separately and fetch it from my original GraphQL API.

**Comment by lukeburns** [comment]
Maybe the important thing is allowing developers to split out resolvers into lambdas as they see fit and simply making it easy and pleasant to build and maintain GraphQL endpoints with Now. E.g. a Now builder that took in a GraphQL schema, resolvers, and lambdas, glues them together in the right way, and spits out a service.

**Comment by rauchg** [comment]
Agreed @lukeburns

**Comment by jrhorn424** [comment]
How can I help? I’m building out some features for an application with GraphQL and want to use now. I’m following the conversation here, but if there’s something I can do in the way of documentation or anything else, I’d like to.

**Comment by lukeburns** [comment]
Started toying with a simple graphql endpoint builder: https://github.com/lukeburns/now-graphql. It takes an entrypoint that exports `{ schema, resolvers }` and spits out a service using [express-graphql](https://github.com/graphql/express-graphql):

```js
module.exports = {
  schema: `
    type Query {
      hello: String
    }
  `,
  resolvers: {
    hello: () => `hello world`
  }
}
```

@rauchg, is it possible to expose the deployment url as an environment variable? If so, it would be very easy to split and compose / make calls across endpoints. Something like the following.

```js
// index.js
const { request } = require('graphql-request')

module.exports = {
  schema: `
    type Query {
      greeting: String
    }
  `,
  resolvers: {
    greeting: async function () {
      return await request(`${process.env.DEPLOYMENT_URL}/hello`, `
        query {
          hello
        }
      `)
    }
  }
}
```

**Comment by jrhorn424** [comment]
@lukeburns I’m working on this and hoping to write some thoughts down for an article. I’ll try out your builder in production on a low-volume project and see how it goes.

**Comment by lukeburns** [comment]
@konsumer, if we find a way to access the deployment url programmatically from within a deployment (or some other way of interacting with other lambdas in the same deployment), then we can come up with ways of stitching together graphql microservices (good to know graphql-proxy exists thx!). A monolambda may even be the best way to go—it's not clear to me yet when splitting a graphql service into multiple is beneficial. @rauchg may have thoughts.

**Comment by konsumer** [comment]
@lukeburns honestly, I'd be happy enough with a monolambda for my use-cases, as long as it was built from many files (again putting all my typedefs, resolvers, and schemaDirectives in the same file as the service definition is a bit painful.)

For now, I guess I'll make a custom monolambda builder that takes a config `src` to assemble a bunch of files. I imagine a config that looks like this:

```js
module.exports = {
  // globs, relative to config file
  schemaDirectives: './schemaDirectives.js',
  typeDefs: './schema/**/*.graphql',
  resolvers: './resolvers/**/*.js',
  
  // apollo-server options here
  introspection: true,
  context: orig => orig,
  playground: { settings: { 'request.credentials': 'same-origin' } }
}
```

I think this will resolve my use-case until I hit a scaling bottleneck and need to work out a better lambda splitting scheme. It will still be better than an EC2 running my service, so I'll be happy enough with it.

I thought more about it, and maybe another way to approach it, for better code-splitting, would be to make 2 builders:

* `graphql-service` - takes all the typedefs, resolvers, and schemaDirectives defined in a config file and smoosh them into a mini graphql server
* `graphql-proxy` - grab a list of all the `graphql-service` typedefs, and generate resolvers that proxy to their lambdas

This would be workable, but still be a pain with any shared type or especially schemaDirectives. For example, I generally have a shared schemaDirective that handles auth & permissions:

```graphql
enum AuthRole {
  VERIFIED
  EDITOR
  ADMIN
  DEV
}

directive @auth(role: AuthRole, roles: [AuthRole]) on FIELD | FIELD_DEFINITION
```

```js
class AuthDirective extends SchemaDirectiveVisitor {
   visitFieldDefinition (field) {
     const requiredText = `Requires ${roles.length ? roles.join(', ') : 'ANY'} role${roles.length > 1 ? 's' : ''}`
     field.description = `${field.description} ${requiredText}.`
     field.resolve = (obj, args, { req, ...ctx }) => {
       // check JWT headers or whatever
     }
  }
}
export default { auth: AuthDirective }
```

This makes it so I don't have to worry about auth on individual resolvers, I just add `@auth` or `@auth([VERIFIED, EDITOR])` on fields that need it, in my schema definitions.

I guess I could just put these sorts of things in seperate npm packages, and just reuse them on multiple services, and redefine them a bunch, but it seems less than ideal.

**Comment by lukeburns** [comment]
You may be able to use your first example as is! I did something similar here: https://github.com/lukeburns/now-examples/tree/master/graphql

Or using the [now-graphql](https://GitHub.com/lukeburns/now-graphql) builder, you would just merge all your typedefs and resolvers, and export the merged configuration.

**Comment by konsumer** [comment]
ooh, I started working on my own builder, but I see now your builder would probably work! Thanks, I will try it out and report issues over there.
