### ISSUE TITLE
Can we add MySQL Server on laravel and adonisjs example?

### ISSUE THREAD

**Issue by jericopulvera** [zeit/now-examples#77]
Is there anyone who can add mysql-server with a generated database app_name
then run migrations and seed?

**Comment by jericopulvera** [comment]
‘’’FROM mhart/alpine-node:10 as build
WORKDIR /usr/src
COPY package.json ./
RUN yarn --production
COPY . .

// DOCKER COMMAND TO CREATE AND RUN MYSQL SERVER WITH A DATABASE NAMES "homestead"

RUN adonis migration:run
RUN adonis migration:seed

FROM mhart/alpine-node:base-10
WORKDIR /usr/src
ENV PATH="./node_modules/.bin:$PATH"
ENV NODE_ENV="production"
ENV ENV_SILENT="true"
COPY --from=build /usr/src .
EXPOSE 3333
CMD ["node", "server.js"]’’’

How do I add mysql with created databased on docker build ?

I’ve been trying but stil cant get it to work.

**Comment by pawelsas** [comment]
Hey @jericopulvera did you solve it?
Could you give me a hint?
