### ISSUE TITLE
All https://now-examples.now.sh/ examples are "Failed to deploy"

### ISSUE THREAD

**Issue by zigomir** [zeit/now-examples#98]
Opening https://now-examples.now.sh/ is currently rendering

![screen shot 2018-09-28 at 11 30 04 pm](https://user-images.githubusercontent.com/957321/46241985-170c3280-c377-11e8-9342-472c06226c05.png)

Although I see I can open most of them.

Maybe `token` from https://github.com/zeit/now-examples/blob/master/meta/deploy#L6 is wrong

**Comment by joecohens** [comment]
Thank you @zigomir, we have fixed this issue!
