### ISSUE TITLE
How to measure size and why it is important

### ISSUE THREAD

**Issue by zigomir** [zeit/now-examples#99]
For example, `node-micro` says it's 19.6MB. I cloned repo and did this

```sh
cd now-examples/node-micro
docker build -t node-micro .
docker images
```

and I get

```
REPOSITORY    TAG                 IMAGE ID            CREATED             SIZE
node-micro    latest              488c3fd0c38e        19 minutes ago      47.3MB
```

Also, explanation why size is important. And/if there are any limits up to what image size do you support or recommend.

**Comment by joecohens** [comment]
Thank you so much for the effort you have put into this issue! 😊

We are closing it for now since it is not applicable to our newest release Now 2.0.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
